language: python
python:
  - "2.7"
# command to install dependencies
install:
    - pip install pytest pytest-cov
# command to run tests
script:
  - pytest -vv tests/tests_asm_encoder.py # or py.test for Python versions 3.5 and below